Repository ansible/ansible-ai-connect-service, pull requests merged in 2025-03, with the labels that each got.

#1548 add ansible_base to pyproject
  pyproject.toml
  requirements-aarch64.txt
  requirements-x86_64.txt
  requirements.in
Labels: bug

#1560 add env vars to compose.yaml
  tools/docker-compose/compose.yaml
Labels: enhancement

#1574 AAP-41904: bump django-oauth-toolkit to 3.0.1
  pyproject.toml
  requirements-aarch64.txt
  requirements-x86_64.txt
  requirements.in
Labels: pr-deployment

#1575 tekton/pr-deployment: always push the tag
  .tekton/ansible-ai-connect-service-pull-request.yaml
Labels: pr-deployment
